
language: c++


matrix:
  include:
    - os: linux
      compiler: gcc
      sudo: required
    - os: linux
      compiler: clang
      sudo: required
    - os: osx
      compiler: gcc
    - os: osx
      compiler: clang

addons:
  apt:
    packages:
    - cmake

script:
 - ./build.py

