language: minimal

stages:
  - setup
# - check

jobs:
  include:
    - stage: setup
      name: "Linux Clang 11"
      os: linux
      dist: focal
      addons: &clang11
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-11 main"
              key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
          packages:
            - clang-11
            - libc++-11-dev
            - libc++abi-11-dev
            - cmake
            - git
            - python3.8
            - python3-pip
      script:
        - clang-11 --version
        - cmake --version
        - python3 --version
      env:
        - MATRIX_EVAL="CC=clang-11.0 && CXX=clang++-11.0"
    - stage: setup
      name: "Linux GCC-10"
      os: linux
      dist: focal
      addons: &clang11
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-10
            - gcc-100
            - cmake
            - git
            - python3.8
            - python3-pip
      script:
        - gcc-10 --version
        - g++-10 --version
        - cmake --version
        - python3 --version
      env:
        - MATRIX_EVAL="CC=gcc-10 && CXX=g++-10"

script: 
  - echo "this script ${MATRIX_EVAL}"

before_install:
  - echo "${MATRIX_EVAL}"