
language: c++


matrix:
  include:
    - os: linux
      compiler: gcc
      sudo: required
    - os: linux
      compiler: clang
      sudo: required
    - os: osx
      compiler: gcc
    - os: osx
      compiler: clang

addons:
  apt:
    sources:
    - george-edison55-precise-backports 
    packages:
    - cmake
    - cmake-data

script:
 -  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "This is Linux"; fi; ./build.py

