language: minimal

stages:
  - setup
# - check

jobs:
  include:
    - stage: setup
      os: linux
      dist: focal
      addons: &clang11
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-11 main"
              key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
          packages:
            - clang-11
            - libc++-11-dev
            - libc++abi-11-dev
            - cmake
      env:
        - MATRIX_EVAL="CC=clang-11.0 && CXX=clang++-11.0"

script: 
  - echo "this script ${MATRIX_EVAL}"

before_install:
  - echo "${MATRIX_EVAL}"