language: c++
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
          - sourceline: "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-11 main"
            key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
      packages:
      - clang-tools-11
      - clang-11
      env:
        - MATRIX_EVAL="CC=clang-11.0 && CXX=clang++-11.0"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-10
            - gcc-10
      env:
        - MATRIX_EVAL="CC=gcc-10 && CXX=g++-10"
    - os: osx
      osx_image: xcode12.5
      env:
        - MATRIX_EVAL="CLANG"
    - os: osx
      osx_image: xcode12.5
      env:
        - MATRIX_EVAL="brew install gcc && CC=gcc && CXX=g++"
    - os: osx
      osx_image: xcode12.5
      env:
        - MATRIX_EVAL="brew install gcc@10 && CC=gcc-10 && CXX=g++-10"

script: 
  - echo "this script ${MATRIX_EVAL}"

before_install:
  - echo "${MATRIX_EVAL}"