language: c++
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
          - sourceline: "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-11 main"
            key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
      packages:
      - clang-tools-11
      - clang-11
      env:
        - MATRIX_EVAL="CC=clang-11.0 && CXX=clang++-11.0"
    - os: osx
      osx_image: xcode10.3
      env:
        - MATRIX_EVAL="brew install gcc && CC=gcc && CXX=g++"

script: 
  - echo "script: ${MATRIX_EVAL}"

before_install:
  - echo "${MATRIX_EVAL}"