language: c++
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-focal-10.0
          packages:
            - clang-10.0
      env:
        - MATRIX_EVAL="CC=clang-10.0 && CXX=clang++-10.0"
    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="brew install gcc && CC=gcc-7 && CXX=g++-7"
before_install:
  - eval "${MATRIX_EVAL}"